name: mirei
description: "A Mental Wellness App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  http: ^1.2.2
  icons_plus: ^5.0.0
  flutter_swiper_view: ^1.1.8
  glassmorphism: ^3.0.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  just_audio: ^0.9.45
  audio_session: ^0.1.24
  permission_handler: ^12.0.1
  pull_down_button: ^0.10.2
  vector_math: ^2.1.4
  image_picker: ^1.1.2
  flutter_sound: ^9.28.0
  # sqflite: ^2.3.0  # Removed - migrating to Realm
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  path: ^1.9.0
  intl: ^0.20.2
  audio_waveforms: ^1.1.0
  flutter_floating_bottom_bar: ^1.3.0
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.0
  equatable: ^2.0.5
  fl_chart: ^1.0.0
  freezed_annotation: ^3.1.0

  # New dependencies for enhanced features
  realm: ^20.1.1 # Realm database replacement for SQLite
  dio: ^5.8.0+1 # Enhanced HTTP client with caching, pooling, interceptors
  dio_cache_interceptor: ^3.5.0 # HTTP caching for audio streams
  dio_cache_interceptor_hive_store: ^4.0.0 # Hive-based cache storage
  hive: ^2.2.3 # Fast key-value database for caching
  hive_flutter: ^1.1.0 # Flutter integration for Hive
  connectivity_plus: ^6.0.5 # Network connectivity monitoring
  cached_network_image: ^3.4.1 # Image caching
  crypto: ^3.0.3 # For cache key generation
  collection: ^1.18.0 # Additional collection utilities
  youtube_explode_dart: ^2.5.2
  stacked_list_carousel: ^1.1.0
  material_color_utilities: ^0.11.1
  lottie: ^3.1.0
  flutter_shaders: ^0.1.3
  hyper_effects: ^0.3.0+1
  flutter_animate: ^4.5.0
  # Spotify Integration
  spotify: ^0.13.7 # For Web API (works with free users for discovery)
  spotify_sdk: ^3.0.2 # For full playback (Premium users only)
  flutter_dotenv: ^5.1.0 # For environment variables (.env file)

  # Firebase Authentication
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  freezed: ^3.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Shader assets for custom effects (temporarily disabled)
  # shaders:
  #   - shaders/custom_blur.frag
  #   - shaders/morph_transition.frag

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env # Environment variables file
    - assets/images/bg-morning.jpg
    - assets/images/bg-afternoon.jpg
    - assets/images/bg-evening.jpg
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/icons/circle.svg
    - assets/icons/emphasis.svg
    - assets/icons/underline.svg
    - assets/icons/b-circle.svg
    - assets/icons/heptagon.svg
    - assets/icons/message.svg
    - assets/icons/octagon.svg
    - assets/icons/pie-chart.svg
    - assets/icons/meditation.svg
    - assets/images/gradient-2.png
    - assets/images/gradient.png
    - assets/icons/Stress.svg
    - assets/images/lofi.png
    - assets/images/color.jpg
    - assets/images/lofi_cover.png
    - assets/images/rnb_cover.png
    - assets/images/meditation.jpg
    - assets/images/meditation.svg
    - assets/images/lofi_cover.png
    - assets/images/rnb_cover.png
    - assets/animations/Bubble Explosion.json
    - assets/images/window.jpg
    - assets/images/moody.jpg
    - assets/images/walking.png
    - assets/images/tabby_journal.png
    # New emotion icons
    - assets/emotion-icons/angry.svg
    - assets/emotion-icons/awkward.svg
    - assets/emotion-icons/cutesy.svg
    - assets/emotion-icons/dissapointed.svg
    - assets/emotion-icons/happy.svg
    - assets/emotion-icons/neutral.svg
    - assets/emotion-icons/sad.svg
    - assets/emotion-icons/shocked.svg
    - assets/emotion-icons/tired.svg
    - assets/emotion-icons/worried.svg

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
